package proyectoFinal;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.*;
        
public class JF_Menu extends javax.swing.JFrame {
    private Connection conn;

    /**
     * Constructor que recibe la conexión.
     */
    public JF_Menu(Connection conn) {
        this.conn = conn; // Guardamos la conexión
        initComponents(); // Inicializamos los componentes gráficos
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        GestionarServicios = new javax.swing.JButton();
        GestionarClientes = new javax.swing.JButton();
        GestionarUsuarios = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        GestionarVehiculos = new javax.swing.JButton();
        GestionarRefacciones = new javax.swing.JButton();
        Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE MANTENIMIENTO AUTOMOTRIZ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("MENÚ PARA ADMINISTRADORES");

        GestionarServicios.setText("Gestionar Servicios");
        GestionarServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionarServiciosActionPerformed(evt);
            }
        });

        GestionarClientes.setText("Gestionar Clientes");
        GestionarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionarClientesActionPerformed(evt);
            }
        });

        GestionarUsuarios.setText("Gestionar Usuarios");
        GestionarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionarUsuariosActionPerformed(evt);
            }
        });

        jLabel2.setText("Selecciona una opción para continuar");

        GestionarVehiculos.setText("Gestionar Vehiculos");
        GestionarVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionarVehiculosActionPerformed(evt);
            }
        });

        GestionarRefacciones.setText("Gestionar Refacciones");
        GestionarRefacciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionarRefaccionesActionPerformed(evt);
            }
        });

        Salir.setText("Cerrar Sesion");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(GestionarClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GestionarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GestionarRefacciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GestionarVehiculos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GestionarServicios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Salir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel2))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GestionarUsuarios)
                .addGap(18, 18, 18)
                .addComponent(GestionarClientes)
                .addGap(18, 18, 18)
                .addComponent(GestionarVehiculos)
                .addGap(18, 18, 18)
                .addComponent(GestionarRefacciones)
                .addGap(18, 18, 18)
                .addComponent(GestionarServicios)
                .addGap(18, 18, 18)
                .addComponent(Salir)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GestionarServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionarServiciosActionPerformed
        JF_Servicios frameServicios = new JF_Servicios(conn);
        frameServicios.setVisible(true); // Mostrar el nuevo JFrame
        frameServicios.setLocationRelativeTo(this); // Centrar el JFrame en relación al frame actual
    }//GEN-LAST:event_GestionarServiciosActionPerformed

    private void GestionarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionarClientesActionPerformed
        JF_Clientes frameClientes = new JF_Clientes(conn);
        frameClientes.setVisible(true); // Mostrar el nuevo JFrame
        frameClientes.setLocationRelativeTo(this); // Centrar el JFrame en relación al frame actual
    }//GEN-LAST:event_GestionarClientesActionPerformed

    private void GestionarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionarUsuariosActionPerformed
        JF_Usuarios frameUsuarios = new JF_Usuarios(conn);
        frameUsuarios.setVisible(true); // Mostrar el nuevo JFrame
        frameUsuarios.setLocationRelativeTo(this); // Centrar el JFrame en relación al frame actual
    }//GEN-LAST:event_GestionarUsuariosActionPerformed

    private void GestionarVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionarVehiculosActionPerformed
        JF_Vehiculos frameVehiculos = new JF_Vehiculos(conn);
        frameVehiculos.setVisible(true); // Mostrar el nuevo JFrame
        frameVehiculos.setLocationRelativeTo(this); // Centrar el JFrame en relación al frame actual
    }//GEN-LAST:event_GestionarVehiculosActionPerformed

    private void GestionarRefaccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionarRefaccionesActionPerformed
        JF_Refacciones frameRefacciones = new JF_Refacciones(conn);
        frameRefacciones.setVisible(true); // Mostrar el nuevo JFrame
        frameRefacciones.setLocationRelativeTo(this); // Centrar el JFrame en relación al frame actual
    }//GEN-LAST:event_GestionarRefaccionesActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        JOptionPane.showMessageDialog(this, "Gracias por usar el sistema.");
        Autenticar.cerrarSesion();
        ConnectDB.closeConnection();
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Connection conn = ConnectDB.getConnection(); // Obtenemos la conexión a la base de datos

        if (conn == null) {
            System.out.println("Error: No se pudo establecer conexión con la base de datos.");
            return;
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Menu(conn).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GestionarClientes;
    private javax.swing.JButton GestionarRefacciones;
    private javax.swing.JButton GestionarServicios;
    private javax.swing.JButton GestionarUsuarios;
    private javax.swing.JButton GestionarVehiculos;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
